In [ ]:
## Created By Akash Modak ##
## Date 25/06/2020 Time 21:05 ##
import numpy as np 
import pandas as pd
import csv
import io
from google.colab import files
# uploaded = files.upload()
# d = pd.read_csv(io.BytesIO(uploaded['combined1.csv']))

features = []
names = []
# print(data)
with open('final.csv','rt')as f:
  data = csv.reader(f)
  for row in data:
    features.append(np.array(row[0:]))
  
# print(uploaded['combined1.csv'])
# print(d)
features = np.array(features)
print(features)
df_train = pd.read_csv('final.csv')
print('train set: {0}'.format(df_train.shape))
df_train.head(10)

Saving final.csv to final.csv
[['song_id' 'tempo' 'total_beats' ... 'frame_std' 'frame_var' 'label']
 ['1' '129.1992188' '164643' ... '4.649219877' '21.61524547' '4']
 ['2' '151.9990809' '199193' ... '1.129928778' '1.276739044' '4']
 ...
 ['961' '107.6660156' '133404' ... '1.115956794' '1.245359566' '1']
 ['962' '86.1328125' '104247' ... '1.173567726' '1.377261208' '1']
 ['963' '117.4538352' '153341' ... '1.795513679' '3.223869371' '1']]
train set: (963, 56)


song_id       tempo  total_beats  ...  frame_std  frame_var  label
0        1  129.199219       164643  ...   4.649220  21.615245      4
1        2  151.999081       199193  ...   1.129929   1.276739      4
2        3  151.999081       161883  ...   3.537997  12.517425      4
3        4  161.499023       210099  ...   1.572752   2.473548      4
4        5  143.554688       183554  ...   1.372578   1.883970      4
5        6  107.666016       138108  ...   1.282054   1.643663      4
6        7  129.199219       157403  ...   3.403311  11.582525      4
7        8  135.999178       169544  ...   1.354491   1.834647      4
8        9   99.384014       126673  ...   1.002803   1.005614      4
9       10  161.499023       199135  ...   1.241723   1.541875      4

[10 rows x 56 columns]

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt
plt.style.use('dark_background')

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout, Embedding, LSTM

Using TensorFlow backend.


In [ ]:
training_set = df_train.iloc[:,1:54].values

In [ ]:
print(training_set)

[[1.29199219e+02 1.64643000e+05 1.27630233e+03 ... 7.39908000e-04
  8.46715646e+00 4.64921988e+00]
 [1.51999081e+02 1.99193000e+05 1.29346104e+03 ... 1.40814900e-03
  2.59482993e+00 1.12992878e+00]
 [1.51999081e+02 1.61883000e+05 1.21716541e+03 ... 1.44966000e-04
  8.16878005e+00 3.53799729e+00]
 ...
 [1.07666016e+02 1.33404000e+05 1.30788235e+03 ... 2.44099400e-03
  4.02285714e+00 1.11595679e+00]
 [8.61328125e+01 1.04247000e+05 1.27130488e+03 ... 3.44322000e-04
  4.29220862e+00 1.17356773e+00]
 [1.17453835e+02 1.53341000e+05 1.32190517e+03 ... 6.21482000e-04
  5.46133333e+00 1.79551368e+00]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
print(training_set_scaled)

[[0.42222222 0.42632215 0.36471016 ... 0.17761222 0.2403659  0.20791217]
 [0.5751634  0.60561918 0.38202038 ... 0.3407327  0.04347995 0.01975345]
 [0.5751634  0.41199915 0.30505108 ... 0.03238434 0.23036201 0.14850071]
 ...
 [0.27777778 0.26420754 0.39656904 ... 0.59285458 0.09135851 0.01900644]
 [0.13333333 0.11289745 0.35966859 ... 0.08104799 0.10038926 0.02208661]
 [0.34343434 0.36767049 0.41071568 ... 0.14870393 0.13958739 0.05533892]]


In [ ]:
X_train = []
y_train = []
for i in range(60, 963):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
x_val = X_train[-100:]
y_val = y_train[-100:]
X_train = X_train[:-100]
y_train = y_train[:-100]
# print(X_train)

In [ ]:
regressor = Sequential()

regressor.add(LSTM(units = 64, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 64, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 64))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 64, activation='relu'))
regressor.add(Dense(64, activation='relu'))

# regressor.add(Dense(1))

regressor.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4), metrics=['accuracy'])

regressor.fit(X_train, y_train, epochs = 100, validation_data=(x_val,y_val), batch_size = 32)

Train on 803 samples, validate on 100 samples
Epoch 1/100
803/803 [==============================] - 4s 5ms/step - loss: 0.6935 - accuracy: 0.0000e+00 - val_loss: 0.6932 - val_accuracy: 0.0000e+00
Epoch 2/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6932 - accuracy: 0.0125 - val_loss: 0.6931 - val_accuracy: 0.5300
Epoch 3/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6932 - accuracy: 0.2042 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 4/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6931 - accuracy: 0.5243 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 5/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6931 - accuracy: 0.6476 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 6/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6931 - accuracy: 0.7422 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 7/100
803/803 [==============================] - 3s 4ms/step - loss: 0.6931 - accu